version: '3' 

networks:
  internet:
    external: true
  proxy-untrusted:
    external: true
  proxy:
    external: true
  backend:
    internal: true

services: 
  app: 
    #image: mohamnag/nginx-file-browser
    image: nginx
    container_name: avbroot-frontend
    restart: always
#    ports: 
#      - 8080:80
    volumes: 
      - ./ota:/usr/share/nginx/html:ro
    networks:
      - internet
      - proxy-untrusted